version: '3.7'

services:
  appDB:
      container_name: appDB
      image: postgres:14-alpine
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: app_server
        PGDATA: /var/lib/postgresql/data/pgdata
      volumes:
        - ./AppDB/postgres-data:/var/lib/postgresql/data
      ports:
        - '5431:5432'

volumes:
  postgres-data:
