version: '3.7'

services:
  appDB:
      container_name: appDB
      image: postgres:14-alpine
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: app_server
      
        POSTGRES_INITDB_ARGS: --auth=scram-sha-256
      ports:
        - '5431:5432'
      volumes:
        - ./AppDB/postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

#  collector:
#    image: collector
#    ports:
#      - 8080:8080
#    environment:
#      RABBITMQ_EXCHANGE: ws1
#      RABBITMQ_QUEUES: humidity,temperature,heat index,wind speed,wind direction,pressure,day,rain quantity
#    restart: on-failure
#    depends_on:
#      - rabbitmq
